### PR TITLE
Added SPM support

### PR DESCRIPTION
**Pull request by AppleArealidea**

### CODE REVIEW

**Comment by meilbn** [comment]
Thank you for pull request.

**Comment by AppleArealidea** [comment]
@meilbn , can you add new tag or release for last commit?

**Comment by meilbn** [comment]
@AppleArealidea Yes, the tag ``1.1.1`` has been created

**Comment by meilbn** [comment]
I am a bit surprised that this repository is still being used. I will find some time to improve it again.

**Comment by AppleArealidea** [comment]
Yes, we are using this project to debug our application. Thanks for the work!

**Comment by meilbn** [comment]
You're welcome, and I'm also very pleased that this project has been helpful to you.

**Pull request merged**
